# Generated by Django 3.2.16 on 2023-03-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_rename_skill_skills_skill_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='AllSkills',
        ),
        migrations.RenameField(
            model_name='allskills',
            old_name='skill_name',
            new_name='skill',
        ),
    ]
